version: 2

models:

  # ======================
  # DIMENSIONS
  # ======================
  - name: dim_customer_history
    description: >
      Historical customer dimension for tracking changes over time. test
      ```sql
      SELECT
        customer_hk,
        company_hk,
        customer_id,
        company_id,
        first_name,
        last_name,
        company_name,
        email_addr,
        country,
        customer_tier,
        risk_tolerance,
        effective_from,
        record_source,
        effective_to
      FROM raw_sf.dim_customer_history
      LIMIT 100
      ```
    meta:
      owner: "@dataops_team"
    columns:
      - name: customer_hk
        description: Unique hash key for the customer.
        data_tests:
          - not_null
          - relationships:
              to: ref('hub_customer')
              field: customer_hk

      - name: company_hk
        description: Unique hash key for the company.
        data_tests:
          - relationships:
              to: ref('hub_company')
              field: company_hk

      - name: customer_id
        description: Business key for the customer.
        data_tests: [not_null]

      - name: company_id
        description: Business key for the company.

      - name: first_name
        description: First name of the customer.

      - name: last_name
        description: Last name of the customer.

      - name: company_name
        description: Name of the company associated with the customer.

      - name: email_addr
        description: Email address of the customer or company.

      - name: country
        description: Country of the customer.

      - name: customer_tier
        description: Tier level of the customer (e.g., Silver, Gold, Platinum).

      - name: risk_tolerance
        description: Risk tolerance level of the customer.

      - name: effective_from
        description: Timestamp when this record became effective.
        data_tests: [not_null]

      - name: record_source
        description: Source system of the record.
        data_tests: [not_null]

      - name: effective_to
        description: Timestamp when this record was superseded.

  - name: dim_customer
    description: Customer dimension for analytics and AI features.
      ```sql
      SELECT
        customer_hk,
        customer_id,
        first_name,
        last_name,
        company_name,
        email_addr,
        country,
        customer_tier,
        risk_tolerance,
        effective_from,
        record_source
      FROM raw_sf.dim_customer
      LIMIT 100;
      ```
    meta:
      owner: "@dataops_team"
    columns:
      - name: customer_hk
        description: Unique hash key for the customer.
        data_tests: [not_null, unique]

      - name: customer_id
        description: Business key for the customer.
        data_tests: [not_null]

      - name: first_name
        description: First name of the customer.

      - name: last_name
        description: Last name of the customer.

      - name: company_name
        description: Name of the company associated with the customer.

      - name: email_addr
        description: Email address of the customer or company.

      - name: country
        description: Country of the customer.

      - name: customer_tier
        description: Tier level of the customer (e.g., Silver, Gold, Platinum).

      - name: risk_tolerance
        description: Risk tolerance level of the customer.

      - name: effective_from
        description: Timestamp when this record became effective.
        data_tests: [not_null]

      - name: record_source
        description: Source system of the record.
        data_tests: [not_null]

  - name: dim_asset
    description: Asset dimension (stocks and crypto).
      ```sql
      SELECT
        asset_hk,
        asset_symbol,
        asset_type,
        record_source,
        base_currency,
        quote_currency,
        price,
        volume,
        market_cap,
        pe_ratio,
        week_52_high,
        week_52_low,
        last_observed_at,
        asset_created_at
      FROM raw_sf.dim_asset
      LIMIT 100;
      ```
    meta:
      owner: "@dataops_team"
    columns:
      - name: asset_hk
        description: Unique hash key for the asset.
        data_tests: [not_null, unique]

      - name: asset_symbol
        description: Ticker symbol for the asset.
        data_tests: [not_null]

      - name: asset_type
        description: Type of the asset (e.g., Stock, Crypto).
        data_tests: [not_null]

      - name: record_source
        description: Source system of the record.
        data_tests: [not_null]

      - name: base_currency
        description: Base currency of the asset.

      - name: quote_currency
        description: Quote currency of the asset.

      - name: price
        description: Latest price of the asset.

      - name: volume
        description: Latest trading volume of the asset.

      - name: market_cap
        description: Market capitalization of the asset.

      - name: pe_ratio
        description: Price-to-Earnings ratio of the asset.

      - name: week_52_high
        description: 52-week high price of the asset.

      - name: week_52_low
        description: 52-week low price of the asset.

      - name: last_observed_at
        description: Timestamp when the asset was last observed.

      - name: asset_created_at
        description: Timestamp when the asset was created in the system.

  # ======================
  # FACTS
  # ======================

  - name: fct_transactions
    description: Transaction fact table.
      ```sql
      SELECT
        transaction_hk,
        transaction_id,
        customer_id,
        customer_hk,
        asset_hk,
        transaction_type,
        quantity,
        price_per_unit,
        transaction_amount,
        fee_amount,
        transaction_timestamp,
        data_date,
        record_source,
        load_timestamp
      FROM raw_sf.fct_transactions
      ORDER BY data_date DESC LIMIT 100;
      ```
    meta:
      owner: "@dataops_team"
    columns:
      - name: transaction_hk
        description: Unique hash key for the transaction.
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('hub_transaction')
              field: transaction_hk

      - name: transaction_id
        description: Business key for the transaction.
        data_tests: [not_null]

      - name: customer_id
        description: Business key for the customer.
        data_tests: [not_null]

      - name: customer_hk
        description: Foreign key to the customer dimension.
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_hk

      - name: asset_hk
        description: Foreign key to the asset dimension.
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_asset')
              field: asset_hk

      - name: transaction_type
        description: Type of transaction (e.g., Buy, Sell).
        data_tests: [not_null]

      - name: quantity
        description: Quantity of the asset transacted.
        data_tests: [not_null]

      - name: price_per_unit
        description: Price per unit of the asset at the time of transaction.
        data_tests: [not_null]

      - name: transaction_amount
        description: Total amount of the transaction.
        data_tests: [not_null]

      - name: fee_amount
        description: Fee amount associated with the transaction.

      - name: transaction_timestamp
        description: Timestamp when the transaction occurred.
        data_tests: [not_null]

      - name: data_date
        description: Date of the transaction for reporting purposes.
        data_tests: [not_null]

      - name: record_source
        description: Source system of the record.
        data_tests: [not_null]

      - name: load_timestamp
        description: Timestamp when the record was loaded.
        data_tests: [not_null]

  - name: fct_asset_prices
    description: Time-series asset prices for analytics and AI models.
      ```sql
      SELECT
        asset_hk,
        asset_symbol,
        asset_type,
        observed_at,
        price_date,
        price,
        volume,
        price_source,
        asset_class
      FROM raw_sf.fct_asset_prices
      LIMIT 100;
      ```
    meta:
      owner: "@dataops_team"
    columns:
      - name: asset_hk
        description: Foreign key to the asset dimension.
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_asset')
              field: asset_hk

      - name: asset_symbol
        description: Ticker symbol for the asset.
        data_tests: [not_null]

      - name: asset_type
        description: Type of the asset (e.g., Stock, Crypto).
        data_tests: [not_null]

      - name: observed_at
        description: Timestamp when the price was observed.
        data_tests: [not_null]

      - name: price_date
        description: Date of the price observation.
        data_tests: [not_null]

      - name: price
        description: Price of the asset at the observed time.
        data_tests: [not_null]

      - name: volume
        description: Trading volume of the asset at the observed time.

      - name: price_source
        description: Source of the price data.

      - name: asset_class
        description: Class of the asset (e.g., Equity, Cryptocurrency).

  - name: fct_news_events
    description: Fact table for news events related to assets.
      ```sql
      SELECT
        news_hk,
        asset_hk,
        asset_symbol,
        asset_type,
        published_date,
        title,
        description,
        url,
        news_source
      FROM raw_sf.fct_news_events
      LIMIT 100;
      ```
    meta:
      owner: "@dataops_team"
    columns:
      - name: news_hk
        description: Unique hash key for the news event.
        data_tests:
          - not_null
          - relationships:
              to: ref('hub_news')
              field: news_hk
      - name: asset_hk
        description: Foreign key to the asset dimension.
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_asset')
              field: asset_hk
      - name: asset_symbol
        description: Ticker symbol for the asset.
        data_tests: [not_null]
      - name: asset_type
        description: Type of the asset (e.g., Stock, Crypto).
        data_tests: [not_null]
      - name: published_date
        description: Date when the news was published.
        data_tests: [not_null]
      - name: title
        description: Title of the news article.
      - name: description
        description: Brief description or summary of the news article.
      - name: url
        description: URL link to the full news article.
      - name: news_source
        description: Source of the news article.
  
  
  - name: fct_asset_news_impact
    description: Fact table measuring news impacting asset prices across different timespans.
      ```sql
      SELECT
        news_hk,
        asset_hk,
        news_date,
        price_t0,
        price_t1,
        price_t3,
        price_t7,
        return_1d,
        return_3d,
        return_7d
      FROM raw_sf.fct_asset_news_impact
      LIMIT 100;
      ```
    meta:
      owner: "@dataops_team"
    columns:
      - name: news_hk
        description: Unique hash key for the news event.
        data_tests:
          - not_null
          - relationships:
              to: ref('hub_news')
              field: news_hk
      - name: asset_hk
        description: Foreign key to the asset dimension.
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_asset')
              field: asset_hk
      - name: news_date
        description: Date of the news event.
        data_tests: [not_null]
      - name: price_t0
        description: Asset price at time t0 (news date).
      - name: price_t1
        description: Asset price 1 day after the news date.
      - name: price_t3
        description: Asset price 3 days after the news date.
      - name: price_t7
        description: Asset price 7 days after the news date.
      - name: return_1d
        description: Asset return 1 day after the news date.
      - name: return_3d
        description: Asset return 3 days after the news date.
      - name: return_7d
        description: Asset return 7 days after the news date.
  
  - name: fct_asset_price_comparison
    description: Fact table for asset price comparisons over various sources (Binance, coingecko, yfinance).
      ```sql
      SELECT
        asset_hk,
        price_date,
        price_binance,
        price_coingecko,
        price_yfinance
      FROM raw_sf.fct_asset_price_comparison
      LIMIT 100;
      ```
    meta:
      owner: "@dataops_team"
    columns:
      - name: asset_hk
        description: Foreign key to the asset dimension.
        data_tests:
          - not_null
          - relationships:
              to: ref('fct_asset_prices')
              field: asset_hk
      - name: price_date
        description: Date of the price observation.
        data_tests: [not_null]
      - name: price_binance
        description: Asset price from Binance on the given date.
      - name: price_coingecko
        description: Asset price from CoinGecko on the given date.
      - name: price_yfinance
        description: Asset price from Yahoo Finance on the given date.
  
  - name: dim_company
    description: Fact table for company information related to assets.
      ```sql
      select
          company_hk,
          company_id,
          company_name,
          company_type,
          company_email,
          country,
          year_founded,
          tax_number,
          office_primary_location,
          registration_date,
          load_timestamp,
          source
      FROM raw_sf.fct_company
      LIMIT 100;
      ```
    meta:
      owner: "@dataops_team"
    columns:
      - name: company_hk
        description: Unique hash key for the company.
        data_tests: [not_null, unique]
      - name: company_id
        description: Business key for the company.
        data_tests: [not_null]
      - name: company_name
        description: Name of the company.
      - name: company_type
        description: Type of the company (e.g., Public, Private).
      - name: company_email
        description: Contact email of the company.
      - name: country
        description: Country where the company is located.
      - name: year_founded
        description: Year the company was founded.
      - name: tax_number
        description: Tax identification number of the company.
      - name: office_primary_location
        description: Primary office location of the company.
      - name: registration_date
        description: Date when the company was registered.
      - name: load_timestamp
        description: Timestamp when the record was loaded.
        data_tests: [not_null]
      - name: source
        description: Source system of the record.

  # ======================
